on: pull_request
name: Changelog Reminder
jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Changelog Reminder
        uses: peterjgrainger/action-changelog-reminder@v1.2.0
        with:
          changelog_regex: "CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Changelog Tool
        uses: rcmachado/changelog-action@v1
        with:
          args: diff CHANGELOG.md <(/changelog fmt CHANGELOG.md) --color -u