on: pull_request
name: Changelog Reminder
jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Changelog Reminder
        uses: peterjgrainger/action-changelog-reminder@v1.2.0
        with:
          changelog_regex: "CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Changelog Tool
        uses: rcmachado/changelog-action@v1
        with:
          args: init --output CHANGELOG.md --compare-url https://keepachangelog.com/en/1.0.0/